### ISSUE TITLE
This is not a bug report

### ISSUE THREAD

**Issue by lynxlynxlynx** [Balrog994/goblin-defence#11]
Hey, just trying to get in touch for GemRB [history purposes](https://gemrb.github.io/History.html#gemrb-is-born) (20 year anniversary). Please shoot me an email if you see this (it's public on my profile).

Thanks

**Comment by Balrog994** [comment]
I think I found your email and replied ;)

**Comment by lynxlynxlynx** [comment]
Great, thanks, will reply soon!
